swagger: "2.0"
info:
  description: "The credit card validator assignment project"
  version: "1.0.0"
  title: "Credit Card Validator Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/api"
schemes:
- "https"
- "http"
paths:
  /creditcard:
    post:
      tags:
      - "creditcard"
      summary: "Send the payload to validate my credit card"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Creditcard Object"
        required: true
        schema:
          $ref: "#/definitions/CreditCard"
      responses:
        200:
          description: "You credit card is valid"
          schema:
            $ref: "#/definitions/CreditCardResponse"
        400:
          description: "Credit card number or Expired Date is in valid"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  CreditCard:
    type: "object"
    properties:
      CARD_NO:
        type: "integer"
        format: "int64"
        example: 4000000000000001
      EXPIRE_DATE:
        type: "string"
        example: "012020"
  CreditCardResponse:
    type: "object"
    properties:
      Result:
        type: "string"
        example: "Valid"
      CardType:
        type: "string"
        example: "Visa"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"